### ISSUE TITLE
Popover export decallage

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#105]

**Comment by beber32** [comment]
Je n'ai pas réussi à coriger ce pb.
Une solution est de placer les popovers à gauche et non en dessous.

**Comment by salimkanoun** [comment]
C good !

**Comment by salimkanoun** [comment]
Je pense qu'il y a un problème dans la construction de la div export qui provoque le décalage.

Cf capture screen sur smartphone, sur export la table sort de la div alors que sur les autres tools ça se passe bien
![Screenshot_20200510-101057](https://user-images.githubusercontent.com/25229822/81494165-d12f8400-92a6-11ea-980b-945d57a2e105.jpg)
![Screenshot_20200510-101107](https://user-images.githubusercontent.com/25229822/81494171-db518280-92a6-11ea-861d-c840db5afae8.jpg)

**Comment by salimkanoun** [comment]
@beber32 
J'ai résolu le probleme en ajoutant
wrapperClasses="table-responsive"
dans les props des nested tables
