### ISSUE TITLE
Warning a apparition Overlay

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#113]
A l'apparition de l'overlay on a le warning suivant

Popper: CSS "margin" styles cannot be used to apply padding between the popper and its reference element or boundary. To replicate margin, use the `offset` modifier, as well as the `padding` option in the `preventOverflow` and `flip` modifiers. 
    in Overlay (created by Overlay)
    in Overlay (at AnonTool.js:44)
    in AnonTool (created by ConnectFunction)
    in ConnectFunction (at ToolsPanel.js:74)
    in ToolsPanel (created by ConnectFunction)
    in ConnectFunction (at NavBar.js:36)
    in NavBar (at App.js:51)
    in App (at src/​index.js:19)

**Comment by beber32** [comment]
Même problème avec les dropDown

**Comment by beber32** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/5081

Faire une mise à jour de la librairie ?

**Comment by salimkanoun** [comment]
Ah oui on est sur la 1.0.0 et y a la 1.0.1 sorti y a 20 jours,
Faut tenter en effet. Je le ferai ce soir si tu veux

Le mar. 12 mai 2020 à 14:41, Sylvain Berthier <notifications@github.com> a
écrit :

**Comment by beber32** [comment]
La mise à jour était nécessaire en effet.

**Comment by salimkanoun** [comment]
Great !
