### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by beber32** [salimkanoun/Orthanc-Tools-JS#122]
Afficher les Jobs en cours pour l'administrateur

**Comment by salimkanoun** [comment]
@beber32 , tes action marchent bien pas de soucis,

dans cette page de job faudrait gerer un auto refresh qui relance l api qui get les job tte les secondes (cf ce que jai fait pour la page robot)

si echec d'un appel api faire un reactifty, par exemple si tu resumit un job succes orthanc refuse (ca aaparait dans les logs d orthanc) mais t a pas de reactify pour dire que l operation a echouee

**Comment by salimkanoun** [comment]
Tres bien,
J'ai refactor un peu en passant l'API /jobs en /jobs?expand pour avoir 1 seul appel sur le back a chaque fois.
J'ai refactor un peu aussi le stockage des data, je fais tout sur une seule clé dans le state
