### ISSUE TITLE
La table ne se rafraichie pas après un delete patient

### ISSUE THREAD

**Issue by beber32** [salimkanoun/Orthanc-Tools-JS#125]
Lorsqu'on supprime un patient dans orthancContent avec les boutons actions, le patient se supprime mais la table ne se rafraichie pas directement. Obliger de refaire une recherche pour actualiser.

**Comment by salimkanoun** [comment]
et au delete study il faudrait vider la table series (c'est pas forcement la study effacée qui avait le focus mais si on peut pas le gerer on peut vider de force la table series dans tous les cas)

**Comment by salimkanoun** [comment]
Good !
