### ISSUE TITLE
Export Panel ajouter buttons dans le tool flotant

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#137]
Peut etre qu'on peut intéragir directement avec le tool sans passer par la vue principale (qui devient beaucoup plus optionelle)

A reflechir

**Comment by beber32** [comment]
Toujours d'actualité ou on peut close ?

**Comment by salimkanoun** [comment]
Si je pense que ca serait bien de mettre les bouttons d'export locaux directement dans le tools
