### ISSUE TITLE
Panel Modify

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#143]
3 Niveau de modification possible

Patient,
Study
Series

On va pour l'instant limiter la modification au MainDicomTags
A chaque Niveau au montre une table qui correspond au MainDicomTags du niveau correspondant (l'ouverture est déclanché par le boutton d'action qu'on a déjà fait)

Les tables qui affichent les data sont modifiables, si elles ont été modifiée elle changent de couleurs

Une case à cocher pour "Remove private tags"
une case à cocher pour "Delete original ressource" 

Un botton "Modify" qui appelle l'API d'Orthanc 
https://book.orthanc-server.com/users/anonymization.html#modification-of-studies-or-series
+ tj ajouter
 "Force": true

**Comment by salimkanoun** [comment]
J'ai demandé une modification d'Orthanc pour pas avoir à gerer la supression de la ressource de notre coté

https://groups.google.com/forum/#!topic/orthanc-users/CgU-Wg8vDio

**Comment by beber32** [comment]
Instance a ne pas mettre dans la liste (ca dépend du nombre d'image que t'a, pour ca c'est les API Merge / Spit que j'ai jamais utilisé)
Serie Date et Serie Time tu peux pas supprimer mais edition OK (y compris laiser vide)
Modality non supprimable
Les ID non editable (à enlever de la liste) sauf PatientID éditable uniquement
le reste éditable et supprimablel
PatientID ne doit pas etre vide egalement

**Comment by salimkanoun** [comment]
OK pas mal,

Faudrait que tu passe la modification en assyncrhone pour pouvoir dire la progression de la modification
Tu passe le meme boolean que dans anonymisation pour le rendre async
Tu recupere l'Orthanc Id du job et tu le monitor.

Va falloir qu'on reflechisse a un truc pour les opération asynchrone, probablement qu'il faudrai fait une sorte de toastify qui dit que l'opération est en cours comme ca l'utilisateur peut continuer de faire autre chose et le toastify te donne la progression en "flottant" 

J'ai fait disparaitre la checkbox si elle est disabled.

Et il faudrait que tu sorte le component de modify en dehors de l'action button pour mieux separer les class, chaque class ne doit faire qu'une chose
