### ISSUE TITLE
Metadata : Le spinner ne marche pas

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#166]
Le spinner reste bloqué à 0
et j'ai l'erreur suivante

react-dom.development.js:8433 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

**Comment by beber32** [comment]
Pour ma part il marche correctement, as tu fait un npm install ? J'ai rajouté un module 'NumericInput' pour faire le spinner

**Comment by salimkanoun** [comment]
Yes t'es sur chrome ? 
ca a l'air d'un un probleme avec prevent default, spécifique a chrome ?
