### ISSUE TITLE
 AutoQuery : Faire remonter les lignes filtrées et selectionnées

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#192]
Je n'arrive pas a faire remonter les lignes selectionnées et les lignes filtrées des 2 tables ou t'a mis les filtre dans autoquery.
J'ai l'impression que c'est le fait que j'ai un conditional rendernig qui m'empeche de mettre une ref pour recupérer les data.

si t'a des idées sur le probleme je pose.
Sinon y a moyen que tu m'envoie vers le redux les ressources filtrées ?

**Comment by beber32** [comment]
Les ressources filtrées sont envoyées dans le redux
