### ISSUE TITLE
User création / edition

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#222]
Faire une interface de création de users pour l administrateur.

Un user est défini par un username (unique obligatoire), un password, un rôle, un nom, un prénom, un mail (a part le username, password et role tout est optionnel).

L administrateur peut crée, éditer un user existant, en supprimer

On créera un rôle par défaut "user"

**Comment by leocouderc** [comment]
Reste modif du password 
@beber32 @leocouderc 

+ admin non supprimable
