### ISSUE TITLE
Robot anon 

### ISSUE THREAD

**Issue by beber32** [salimkanoun/Orthanc-Tools-JS#242]
-Changer la clé pour les studies anonymized (anonymizedOrthancStudyID)
-Lorsque que je fais une anon, le robot reprend toutes les anons précédantes

**Comment by salimkanoun** [comment]
@beber32 j'ai commit ta branche, j'ai changé la clé comme demandé pour la nouvelle orthanc ID.
Maintenant une nouvelle requette d'anon ne relance pas tout.
En revanche si une requete d'anon est en cours pour l'utilisateur je refuse la nouvelle requete, il faut attendre la fin de la requette précedent pour en lancer une nouvelle.

On va devoir gerer un Pause / Resume / Delete des different Robot

**Comment by beber32** [comment]
La clé des nouvelles studies est toujours setAnonymizedOrthancStudyID

**Comment by salimkanoun** [comment]
@beber32 j'ai corrigé la clé (back et front)

Pour l'anonymize je trouve que l'affichage est trop chargé pendant l'anon, 

Faudrait que le panel d'anon soit completement disabled pendant le processus d'anon, ca serait bien de cacher tous les bouttons et de laisser afficher que les table
Pour decharger peut etre carrement cacher la table d'anon qui pourrait se montrer qu'a la demande ou splitter en 2 tab la liste d'anon et de result.

Faudrait afficher le % de progression dans le circle (cf mon code dans le retrieve robot) 

Y a un truc bizarre aussi quand je fais un anon et que je pousse la liste anonymisée dans l'export il y a des study non anonymisées qui apparaissent dans l'export alors qu'ils devraient tous etre anonymisés vu qu'ils viennent de la liste d'anonymisation faite
