### ISSUE TITLE
Robot Delete

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#248]
A faire

**Comment by salimkanoun** [comment]
@beber32 
Pour le robot delete,
Pour la création du robot peut tu implementer l'API suivante
POST
api/robot/:username/delete
le payload : l'array des orthancID a delete

pour le monitoring c'est GET sur la meme API

L'api va surement buggé (pas testé encore) mais avec le front branché dessus je pourrais debeuger

**Comment by beber32** [comment]
J'ai préparer l'api, elle renvoie une erreur : Cannot read property 'execute' of undefined. 
J'ai l'ai donc mis en commentaire, te faudras juste le décommenter pour débuger

**Comment by salimkanoun** [comment]
@beber32 la creation du robot marche,
Peut tu essayer de suivre la progression et flusher la liste ?
