### ISSUE TITLE
User : Manque la liste des utilisateur existant avec le modify ?

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#252]
Dans l'interface actuelle je vois pas comment modifier un user existant,
il te manque pas le tableau du user avec le button modify sur chaque user pour l'édition?

**Comment by beber32** [comment]
Pour modifier un user : 
-Accéder au panel user dans administration
-Cliquer sur Edit en bas à droite
-Choisir l'user dans le select 
Toute les informations existante de l'user sont reprise dans le form, et quand on clique sur modify ça renvoie les infos de l'user pour les modifier. Si on clique sur delete ça le supprime avec une demande de confirmation (Ce n'est pas encore implémenté)

**Comment by salimkanoun** [comment]
Hum c'est pas tres intuitif,
Je pense que tu devrait mettre un table ou t'a tout les user (after les filter pour rechercher dans les colonne) et un boutton edit pour editer un user dans la liste
