### ISSUE TITLE
Auto-Retrieve Fatal Error

### ISSUE THREAD

**Issue by leocouderc** [salimkanoun/Orthanc-Tools-JS#263]
Quand on essai de "parse CSV" alors qu'il n'y a pas de fichier choisie Alors le client crash
Solution possible : vérifier si il y a un fichier et Sinon afficher un toastify pour indiquer qu'il n'y a pas de fichier

**Comment by salimkanoun** [comment]
Ouais on va changer cette partie de toute facon on va essayer de passer par une dropzone pour lire le fichier
On fera ca plus tard
