### ISSUE TITLE
Cacher les elements non accessible

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#269]
Maintenant qu'on a le systeme de permissions
Dans le Navbar cacher les liens et les tools pour lesquels l'utilisateur n'a pas de droit

**Comment by beber32** [comment]
@salimkanoun J'ai commencé a cacher les éléments en fonction des droit de l'user, il n'y a pas de droit pour 'import' ? 
Il me reste encore à cacher les boutons anon/export/delete

**Comment by salimkanoun** [comment]
Si mais on a appelé ca Upload 
@leocouderc @beber32  est ce que vous pourriez renommer le role upload à Import pour etre homogene partout ?
