### ISSUE TITLE
AnonTool

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#285]
cette fonction sert a rien non ?

    handleClick(){
        //call API Anon 
        this.props.listContent.forEach((content) => {
            console.log("Will anonymize " + content.id + " from " + content.level + " level")
        })
    }

**Comment by beber32** [comment]
Exact, elle servait au début quand l'anon n'était pas encore fonctionelle. Je l'ai supprimée.
