### ISSUE TITLE
Transcode Selector

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#288]
Cette partie je la decomposerai aussi pour soulager la classe export.
Un select de render avec un callback qui update le state dans export

**Comment by beber32** [comment]
Actuellement quand le TS est null j'envoie 'none' à Orthanc est-ce que c'est bon ou pas ? ou il faut que j'envois une string vide ?

**Comment by salimkanoun** [comment]
Non faut pas mettre la clé Transcode pour pas transcoder, elle doit pas apparaitre dans le payload
