### ISSUE TITLE
error dans console

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#294]
j'ai ca sur la page user management

index.js:1 Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (at Users.js:218)
    in fieldset (at Users.js:216)
    in div (created by ModalBody)
    in ModalBody (at Users.js:286)

**Comment by beber32** [comment]
Problème réglé avec le commit sur #280
