### ISSUE TITLE
JWT coockie HTTPOnly

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#339]
hello @leocouderc ,

Tu pourrais regarder ca :  https://website.simplx.fr/blog/2016/09/27/authentification-api-via-jwt-et-cookies/

Pour le JWT on le stocke actuellement dans un coockie, or c'est vulnerable aux attaques car n'importe quel logiciel JS peut theoriquement lire le cookie et transmettre sa valeur à qqun d'autre, récupérer le token pour se connecter ailleurs en volant l'idendité.

Apparement y a une option httpOnly qui securise ca et qui fait que c'est automatiquement injecté dans toutes les requettes. tu pourrais regarder ?

**Comment by leocouderc** [comment]
Actuellement on rajoute "à la main" le cookie aux requêtes grâce à notre fonction updateOptions(option). Et du coup si j'ai bien compris avec le flag httpOnly, ca le fait directement ?
