### ISSUE TITLE
Route to login

### ISSUE THREAD

**Issue by waterponey** [salimkanoun/Orthanc-Tools-JS#353]
When you're logged out (because of time-out for instance) you're not forced to the login page. For instance if you're on http://orthanctooljs/query , even if you refresh you'll get a blank page instead of a going to http://orthanctooljs/ which is a bit tedious since you have to understand you've been logged out and manually modify the URL to log in again.

**Comment by salimkanoun** [comment]
On a apprit à faire ca avec GaelO : 

https://github.com/salimkanoun/GaelO_Frontend

Pré requis : 
Verifier que dans le back on a bien un 401 (Unauthorized) pour les cas ou le token et invalid
et 403 Forbidden dans les cas ou le token est valid mais notre Role Based Access Controle refuse l'acces

On utilise un librarie fetch interceptor qui permet d'ecouter fetch, via cette lib on intercepte les reponse de fetch ou on voit un 401 apparaitre
cf https://github.com/salimkanoun/GaelO_Frontend/blob/master/src/App.js

Dans GaelO, dans la racine du front on met un modal avec un paneau de re-identification, quand l'interceptor voit un 401 il rend ce modal visible pour relancer la requette d'authenfication et avoir un nouveau jetton.
Pour Orthanc Tools JS on peut aussi faire le choix de simplement reorienter vers la page d'accueil si un 401 apprait (je pense que c'est suffisant pour commencer, l'avantage du modal c'est qu'un fois re loggé tu reviens sur le meme page qu'avant mais je pense pas que ca soit nécéssaire pour Orthanc Tools JS)

**Comment by salimkanoun** [comment]
Fixed !
