### ISSUE TITLE
user asignment will be nice

### ISSUE THREAD

**Issue by pacuraremil** [salimkanoun/Orthanc-Tools-JS#394]
hi Salim, this is an amazing project. For me will be nice for each user to have their environment with their uploaded cases. Like right now all users are basically accessing same list of patients just different permissions. So I would like to implement that with a little bit of guidance if this is too complicated. Probably assign logged user for each patient and so each patient can filter and see only their own data. What do you think?

**Comment by salimkanoun** [comment]
hi  @pacuraremil, at this stage OrthancToolsJS is not meant for this.
However in the roadmap we have the idea to link ressources (studies) to "Clinical Studies" to make centers able to build imaging datalake of clinical studies. 
Then it will be possible to give role based access to these groups of ressource. 

Don't expect this in a near feature, for now we are trying to stabilize the application, finish some features that still missing and  cover OrthancToolsJS with tests. 
That's something we may focus on in the next summer.

**Comment by salimkanoun** [comment]
@pacuraremil if you want to contribute the algorithm would be : 
- Make a module to set Studies to "label"
- Make a table in the database to store the label with a ressource. A ressource can have multiple label, so it would be a table that will have a column OrthancStudyID and a column label. 
- Make an API to list the OrthancID of a label 
- Make a front end to show this list.

Then we will have to modify the role by adding an array of "Studies dataset" accessible for each patient.
The access controle will be done with middelware.


To do this you need skills in ExpressJS, Sequelize and React.

**Comment by pacuraremil** [comment]
I will love to help build but I only have experience in PHP/MySQL/CSS and other javascript libraries that I worked with. 
How hard will be to get this out of Docker and develop it like a old fashion web app? They way it is built right now, trying to implement multiple users with their own orthanc dicom datatabase...not sure if this is efficient having 2 containers for each user(web interface+orthanc)
I am listening to suggestions :)
Thanks

**Comment by salimkanoun** [comment]
In progress
