### ISSUE TITLE
DICOM RT DOSE

### ISSUE THREAD

**Issue by Fellas87** [salimkanoun/Orthanc-Tools-JS#411]
Hi.
I installed this tool in my department coupled with orthanc pacs. I work in a radiotherapy center and we would like to use this tool also to perform a query/retrieve from our archive and to be able to review, in addition to the CT and RT STRUCT, also the RT DOSE in OHIF viewer. I have seen that somehow the dose is read from OHIF, but is not associated with CT dataset. Is there an OHIF extension to do this? 
Thanks a lot.
Francesco

**Comment by salimkanoun** [comment]
Hum better to ask OHIF team.
There two way to go to build a viewer for RT (which is also something I keep an eye on)
- OHIF
- Stone of Orthanc (will be included in the next version of OrthancToolsJS).

Both of them has the technology to do so, but both of them will require funding to do these developpement.
So if you are able to fund one of them will be a great contribution to the ecosystem
