### ISSUE TITLE
error dans le back a execution du robot retrieve

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#412]
Voici le log

UnhandledPromiseRejectionWarning: TypeError: Cannot set property '_progress' of undefined
    at Queue.<anonymous> (/home/salim/Dev-Salim/Image_Fetcher/ImageFetcher/BackEnd/model/OrthancQueue.js:44:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

**Comment by oxabz** [comment]
Es-ce que l'erreur a été levé après un redémarrage de othanc-tool-js?  Sinon comment je peux le reproduire ?

**Comment by salimkanoun** [comment]
A l'execution , ca appraissait quand le front recupérait les data du robot pour afficher la progression quand le robot passait en execution
