### ISSUE TITLE
Robot timing

### ISSUE THREAD

**Issue by waterponey** [salimkanoun/Orthanc-Tools-JS#421]
On a docker-compose based installation of orthanc tool js :

When scheduling the robot, it doesn't rely on the server local time but on the universal time. For instance the task scheduled on OTJS to start at 15:00 will start at 16:00 when you're in France in winter (UTC +1).

**Comment by salimkanoun** [comment]
Problem due to TimeZone definition in node container seems to use GMT by default.
The TimeZone can be set using TZ environement variable in docker compose : 

environment:
            TZ: "Europe/Paris"
