### ISSUE TITLE
Robot : Les item passent en validated automatiquement

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#459]
@oxabz sur le robot on dirait que les items sont automatiquement validé mais le robot en sa globalité doit etre validé manuellement
C'est voulu ?

Dans ma 1ere version c'etait lors de la validation manuelle que tous les items étais validés.
Mais si c'est voulu c'est aussi faisable comme ca

**Comment by oxabz** [comment]
Le faire comme dans la première version et pas possible si on veut que tout soit gérer par bull. 
Actuellement on met les éléments dans la queue de validation et on les check. Et la validation crée les jobs de retrieve correspondant aux jobs de validation

**Comment by salimkanoun** [comment]
OK good !
