### ISSUE TITLE
progression robot ne marche plus

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#460]
le robot demarre mais la progression n'est plus calculée

A noter j'ai trouvé un changement sur got, la réponse de got est un objet response ou le contenu est dispo dans response.body (contrairement a request qui rendait directement le body).
Peut etre que c'est lié a ca, à voir (j'ai corrigé dans le reverse proxy à deux endroit mais j'ai peut etre oublié d'autre)

**Comment by salimkanoun** [comment]
pareil pour anonymize le robot marche bien mais n'update pas de progression il passe de 0% a terminé sur le front

**Comment by oxabz** [comment]
Quelle branche ? J'arrive pas à le reproduire sur dev.

**Comment by salimkanoun** [comment]
le dev oui
Ah par contre j'avais un robot que de 1 item c'est peut etre l'explication tout simplement !

**Comment by oxabz** [comment]
Ah oui bah ça viens d'un autre bug que j'ai fix dans une autre pr
