### ISSUE TITLE
Show detail dans anonymisation affiche un tableau vide

### ISSUE THREAD

**Issue by oxabz** [salimkanoun/Orthanc-Tools-JS#472]

**Comment by oxabz** [comment]
Quel est le comportement attendu?

**Comment by oxabz** [comment]
Comportement attendu : https://discord.com/channels/695219745804517467/695220059492057109/811975817600827412

**Comment by oxabz** [comment]
Solution temporaire : Le bouton a été marqué disabled

**Comment by salimkanoun** [comment]
Je pense que c'est devenu useless, avec les tab actuellement tu a une tab qui te montre ta liste d'anonymisation et un qui te montre la progression
Je pense pas qu'il faille aller plus loin
