### ISSUE TITLE
Creating a listening directory for automatic instant import of Dicom to Orthanc

### ISSUE THREAD

**Issue by maximcherv** [salimkanoun/Orthanc-Tools-JS#525]
I think such an option would be very useful, especially for creating a complete automated **instant** CD/DVD burning processes (rather than a scheduled batch import and burning) .
e,g., A Dicom device can be programmed to send a Dicom file after every exam to a designated directory.
Orthanc-Tools will than recognize a new Dicom file and automatically import it to Orthanc, from this point the automated cd/dvd burning process will be triggered.

Great project.

Thanks in advance for your attention.
Max

**Comment by salimkanoun** [comment]
hi @maximcherv,
I think i don't get it yet,
If you have a Dicom device, why just don't you send images to Orthanc through dicom protocol ? 
This way you will trigger the cd burning without having to monitor an external folder.

**Comment by salimkanoun** [comment]
@maximcherv without more information i will consider this issue abandoned
