### ISSUE TITLE
export Fichier locaux  : utiliser le UID du Job ? 

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#589]
Je cherche un moyen de permettre d'identifier les export vers le serveur.
Le fichier généré reste dans le backend donc pour l'admin sys
L'utilisateur doit pouvoir conaitre une clé qui permet de demander ce fichier à l'admin sys

**Comment by oxabz** [comment]
Tu voudrais que la clé soit donnée sous quelle forme ?
Le nom du fichier peut être donné en payload de la tache, une fois fini. Ça évite d'avoir un id de tache qui sont généralement bien long. Et du coup on pourrait avoir un nom de fichier en mode YYYY-MM-DD-KK.zip .

**Comment by salimkanoun** [comment]
Ouais pas mal, oui le timestamp ca peut etre une bonne solution (mais fait en ms car tu peux avoir plusieurs requetes d'export qui arrivent en meme temps sur le back)
