### ISSUE TITLE
How do i listen to incoming dicom files.

### ISSUE THREAD

**Issue by shravan26** [salimkanoun/Orthanc-Tools-JS#690]
Is there an event that listens to incoming dicom files.  I have reviewed the code for monitoring, so i just want to make sure i understand this well. There is a function for makelistener is that what listens to the incoming dicom files? Sorry if the question isn't worded properly if it is difficult to understand i shall write it better.

**Comment by salimkanoun** [comment]
Hi @shravan26 ,

Welcome to the project,

The monitoring is done by the backend (as it need to continue even the user if online)
The monitoring class is here 
https://github.com/salimkanoun/Orthanc-Tools-JS/blob/master/BackEnd/model/monitoring/Orthanc_Monitoring.js

You get this object using this class with use a singleton pattern to be sure only one monitoring service will run in the backend https://github.com/salimkanoun/Orthanc-Tools-JS/blob/master/BackEnd/model/monitoring/MonitoringFactory.js

The monitoring is based on event senting,

your service that needs to monitor orthanc, has to listen to the monitoring singleton, and will a recieve an event each time something is new in Orthanc
see https://github.com/salimkanoun/Orthanc-Tools-JS/blob/master/BackEnd/model/monitoring/autorouting/Autorouting.js
line 55
`_makeListener = () => {
    this.monitoring.on('StableStudy',(orthancID)=>{
      this._jobDispatcher(orthancID)
    })
  }`

**Comment by shravan26** [comment]
Thanks this really helped, also could you explain what the rule and condition is for? I've been trying to figure out the logic but the usage is still a little cloudy for me.

**Comment by salimkanoun** [comment]
For the autorouter we wanted the user to be able to define a set of rule (ex study description and modality) with each one having a condition rule (modality IN PET/N/MR or date > X days...)
To be flexible you have a condition definition and a rule than translate opérator (==, IN, >) into boolean

**Comment by shravan26** [comment]
thanks you so much that, really helpful. Im sort of using this as a reference to build something that connects to horos and pulls data from that into a customised study list. Im closing this issue now. Thank you for your help
