### ISSUE TITLE
How to deploy orthanctoolsjs with docker run command?

### ISSUE THREAD

**Issue by felixlinxk** [salimkanoun/Orthanc-Tools-JS#693]
I've tried multiple times deploying orthanctoolsjs with 'docker run' command, using the environment settings come from the docker-compose.yml, but never succeed. Is there any guidelines or instructions about that?

for example:

docker run -itd \
--name=orthanctoolsjs \
-p 4000:4000 \
-e ORTHANC_ADDRESS: "http://127.0.0.1" \
-e ORTHANC_PORT: "8042" \
-e ORTHANC_USERNAME: "orthanc" \
-e ORTHANC_PASSWORD: "orthanc" \
-e DB_USERNAME: "orthanctoolsjs" \
-e DB_PASSWORD: "orthanctoolsjs" \
-e DB_HOST: "[postgres](http://127.0.0.1)" \
-e DB_PORT: 5432 \
-e DB_NAME: orthanctoolsjs \
--restart=unless-stopped \
salimkanoun/orthanctoolsjs:latest

**Comment by salimkanoun** [comment]
Never tried but it should work also this way

**Comment by salimkanoun** [comment]
You are missing redis env also

**Comment by felixlinxk** [comment]
> You are missing redis env also

I've added redis, but yet it still failed and stopped automatically

docker run -itd
--name=orthanctoolsjs
-p 4000:4000
-e ORTHANC_ADDRESS=http://172.17.0.1
-e ORTHANC_PORT=8042
-e ORTHANC_USERNAME=orthanc
-e ORTHANC_PASSWORD=orthanc
-e DB_USERNAME=orthanctoolsjs
-e DB_PASSWORD=orthanctoolsjs
-e DB_HOST=http://172.17.0.1
-e DB_PORT=5433
-e DB_NAME=orthanctoolsjs
-e REDIS_HOST=http://172.17.0.1
-e REDIS_PORT=6379
-e REDIS_PASSWORD=orthanctoolsjs
--restart=unless-stopped
salimkanoun/orthanctoolsjs:latest

**Comment by salimkanoun** [comment]
What is the error ?

**Comment by felixlinxk** [comment]
> 

The container stopped immediately after I deployed it, if I set the --restart=always, it would constantly restart and stopped.

**Comment by salimkanoun** [comment]
in the log you should see the error message causing the stop

**Comment by felixlinxk** [comment]
> 

Here is what I found with 'docker logs' command:

> @salim.kanoun/orthanctools@0.7.0 migrate /OrthancToolsJs
> sequelize db:migrate


Sequelize CLI [Node: 14.15.4, CLI: 6.2.0, ORM: 6.6.5]

Loaded configuration file "database/config/config.js".
Using environment "production".

ERROR: getaddrinfo ENOTFOUND http

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @salim.kanoun/orthanctools@0.7.0 migrate: `sequelize db:migrate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @salim.kanoun/orthanctools@0.7.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-21T01_49_49_748Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by salimkanoun** [comment]
Your settings are wrong nither database nor redis are http protocols
