### ISSUE TITLE
docker is not running properly

### ISSUE THREAD

**Issue by Scientist786** [salimkanoun/Orthanc-Tools-JS#701]
It gives me the following error
`Sequelize CLI [Node: 14.15.4, CLI: 6.2.0, ORM: 6.6.5]

Loaded configuration file "database/config/config.js".
Using environment "production".

ERROR: connect ECONNREFUSED 127.0.0.1:5432

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @salim.kanoun/orthanctools@0.7.0 migrate: `sequelize db:migrate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @salim.kanoun/orthanctools@0.7.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                             ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-29T20_55_27_158Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm                                                                             and.
yarn run v1.22.5
$ cross-env NODE_ENV=production npm run migrate
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1648587341012-                                                                             0.6741309959576072/node but npm is using /usr/local/bin/node itself. Use the `--                                                                             scripts-prepend-node-path` option to include the path for the node binary npm wa                                                                             s executed with.

> @salim.kanoun/orthanctools@0.7.0 migrate /OrthancToolsJs
> sequelize db:migrate

Sequelize CLI [Node: 14.15.4, CLI: 6.2.0, ORM: 6.6.5]

Loaded configuration file "database/config/config.js".
Using environment "production".

ERROR: connect ECONNREFUSED 127.0.0.1:5432

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @salim.kanoun/orthanctools@0.7.0 migrate: `sequelize db:migrate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @salim.kanoun/orthanctools@0.7.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                             ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-29T20_55_42_291Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm                                                                             and.
`

when I run the command 
`docker run -itd --name=orthanctoolsjs -p 4000:4000 -e ORTHANC_ADDRESS=http://127.0.0.1 -e ORTHANC_PORT=8042 -e ORTHANC_USERNAME=orthanc -e ORTHANC_PASSWORD=orthanc -e DB_USERNAME=orthanctoolsjs -e DB_PASSWORD=orthanctoolsjs -e DB_HOST=localhost -e DB_PORT=5432 -e DB_NAME=orthanctoolsjs -e REDIS_HOST=localhost -e REDIS_PORT=6379 -e REDIS_PASSWORD=orthanctoolsjs --restart=unless-stopped salimkanoun/orthanctoolsjs:latest`

**Comment by salimkanoun** [comment]
Hi I have no bandwith to help you,

However the project is about to restart, so we should have more stable version is some weeks
