### ISSUE TITLE
Composant Delete

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#72]
Composant Delete : 

Ouvert au click du composant delete en haut à droite
=> Soit dans un Modal soit dans la div principale

1) Dans l'action button ajouter un item "Send To Delete List"
2) Le listener de cet item doit passer par Redux => Formation à voir sur Udemy
3) Le composant Delete List consomme la liste des ressource à effacer depuis le reducer
4) L'interface affiche 3 table (non nested) Patients, Studies, Series qui affiche les ressources affichées aux differents niveaux
5) On fera surement un outil pour voir le detail des Patient et studies (à relechir)
6) Un button rouge "Delete" avec un message de confirmation pour lancer la suppression des ressources
7) Les API delete sont celles qu'on connait /niveau/ID methode DELETE. 
8) Deux facons de proceder possible : 
- Faire les appels un à un depuis le frontEnd => Facile mais nécessite que le front reste ouvert pour que la pile s'execute
- Faire une API sur le backEnd qui accepte une liste de ressource à supprimer, qui va ouvrir un robot delete. Le front requetera le robotDelete pour suivre la progression du Delete => Sexy mais plus lourd à implementer, nécéssite de faire du TDD.

**Comment by beber32** [comment]
Il faudra passer par le back, c'est très long de le faire sur le front.

**Comment by salimkanoun** [comment]
@berber32

J'ai refactoré maintenant on en va lister les ressource qu'au niveau study en gardant les réponse orignielles d'orthanc.
Chaque composant consomera ces data et les reoganisera de la facon dont ils ont besoin.
J'ai crée un repertoire "Tools" ou j'ai mis les methode qui permet de transformer les data de orthanc vers des composant pour eviter de dupliquer certaines methodes qu'on va utiliser dans plusieurs composants.

Pour Orthanc Import : 
- J'ai supprimé trop large et j'ai sorti le listener de selection d'étude (désolé), peut tu le remettre pour reconnecter la table Series (avant de commit j'ai fait une copie dans ma branche donc ma branche comporte le code à remettre)
- Je pense que je vais me charger du backend pour eviter de te disperser et que tu continue a veiller à l'architecture du front (qui est beaucoup plus compliquée que le back)
=> pour l'instant fait ton appel du front ligne par ligne et gère un feedback utilisateur de la progression (par exemple les boutton remove disparaissent et sont remplacé par "Deleted" et quand la liste est finie, la table se vide et un message flottant toastify averti que c'est fini)
- Pour le Tool Delete j'ai essayé de dissocier le bouton et l'overlay
1) Oublie ce que je t'ai dit sur le niveau manquant de l'Overlay c'est une errur
2) Y a un bug de positionement de l'overlay, le bug semble etre un probleme de ref (je crois que l'overlay sait ou il doit se positionner en regardant la ref du composant qui l'a trigger), j'ai mis deux liens dans la classe du delete componant si tu peux essayer de debeuger, ca serait plus propre d'avoir le trigger et l'overlay dans 2 composant distincts
- Regarde les bouttons remove dans le panel delete, ils vident toute la liste, soit c'est une erreur d'appel de méthode soit je me suis tromper dans le refac du reducer (normalement maintenant c'est ultra simple d'enlever une ressource, on loop sur l'array et on enleve les items qui matchent niveau patient ou study)

**Comment by salimkanoun** [comment]
Pour le Delete j'ai fait marché le remove et le empty 
Quand on click sur le lancement du delete il faudra prévoir un message de confirmation comme pour le restart / shutdown d'orthanc

**Comment by salimkanoun** [comment]
Well Done !
