### ISSUE TITLE
Ohif View Incorrectly

### ISSUE THREAD

**Issue by Mengyao-Li** [salimkanoun/Orthanc-Tools-JS#796]
hello, thanks for your work, when I used the project, I meet a problem, I pull the lasted docker image and also make the image, but both of them view in ohif seem to be wrong,
e.g. here is the result viewed in ohif. The image appears to be split into two parts, with the right one moved to the left
<img width="1257" alt="截屏2023-05-17 11 49 44" src="https://github.com/salimkanoun/Orthanc-Tools-JS/assets/49806493/bce4faf2-49f5-4782-a0e1-fc1cd1449086">

Here is the result viewed in Stone,the result is the right
<img width="1256" alt="截屏2023-05-17 11 52 00" src="https://github.com/salimkanoun/Orthanc-Tools-JS/assets/49806493/6a7e4fc5-a449-48ea-bcb7-182b56b18234">
I also upload the dicom file to the demo on ohif website, it seems right.
<img width="1391" alt="截屏2023-05-17 13 27 43" src="https://github.com/salimkanoun/Orthanc-Tools-JS/assets/49806493/6971f9d8-a91e-44f2-99b0-4f500bcfaafa">
looking forward to your reply

**Comment by salimkanoun** [comment]
Yes it have been fixed in the latest docker image 3D ago. please repull the latest image
