### ISSUE TITLE
Unable to setup https

### ISSUE THREAD

**Issue by tanimraja1** [salimkanoun/Orthanc-Tools-JS#818]
using the following docker-compose file, the usual proxypass configuration for apache httpd is not working and there is no documentation containing https setup. Please help.
`version: "2"
#if needed to map the orthancPACS to a different hard disk device (after mounting it in path)
# volumes: ["/home/petctviewer/orthanc:/var/lib/orthanc/db:Z"]

networks:
  web:
    external: true
  internal:
    external: false

services:

    orthanctoolsjs:
        image: ghcr.io/salimkanoun/orthanc-tools-js:latest
        container_name: orthanctoolsjs
        restart: unless-stopped
        ports: ["8080:4000"]
        depends_on: [ postgres ]
        volumes: ["orthanctoolsjs:/OrthancToolsJs/data:Z"]
        environment:
            TZ: "Europe/Paris"
            ORTHANC_ADDRESS: "http://orthanc"
            ORTHANC_PORT: "8042"
            ORTHANC_USERNAME: "salim"
            ORTHANC_PASSWORD: "salim"
            DOMAIN_PROTOCOL: "http"
            DOMAIN_ADDRESS: "localhost"
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
            REDIS_PASSWORD: ""
            DB_USERNAME: "postgres"
            DB_PASSWORD: "postgres"
            DB_HOST: "postgres"
            DB_PORT: 5432
            DB_NAME: orthanctoolsjs
        networks:
          - internal
          - web
        labels:
        - "traefik.enable=true"
        - "traefik.port=4000"
        - "traefik.http.routers.blog.rule=Host(`0e44be91-4285-440b-a132-c6580851eed7.pub.instances.scw.cloud`)"
        - "traefik.http.routers.blog.entrypoints=websecure"
        - "traefik.docker.network=web"  
    
    redis:
        image: redis:alpine
        networks:
          - internal

    postgres:
        container_name: postgresorthanctoolsjs
        image: postgres:13.1
        networks:
          - internal
        environment:
            POSTGRES_DB : "orthanctoolsjs"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: unless-stopped

    orthanc:
        image: osimis/orthanc:23.4.0
        container_name: orthanctoolsjsorthanc
        restart: unless-stopped
        ports: ["8042:8042"]
        volumes: ["orthanc:/var/lib/orthanc/db:Z"]
        networks:
          - internal
        environment:
            NEURO_PLUGIN_ENABLED : "true"
            ORTHANC__NAME: "OrthancToolsJS"
            ORTHANC__DICOM_SERVER_ENABLED: "true"
            ORTHANC__DICOM_MODALITIES_IN_DATABASE: "true"
            ORTHANC__DATABASE_SERVER_IDENTIFIER : "Orthanc1"
            ORTHANC__ORTHANC_PEERS_IN_DATABASE: "true"
            DICOM_WEB_PLUGIN_ENABLED: "true"
            OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
            PYTHON_PLUGIN_ENABLED: "true"
            TRANSFERS_PLUGIN_ENABLED: "true"
            WORKLISTS_PLUGIN_ENABLED: "true"
            ORTHANC__REGISTERED_USERS: |
                {"salim": "salim"}
            ORTHANC__DICOM_WEB__ENABLE: "true"
            ORTHANC__DICOM_WEB__ROOT: "/dicom-web/"
            ORTHANC__DICOM_WEB__ENABLEWADO: "true"
            ORTHANC__DICOM_WEB__WADOROOT: "/wado"
            ORTHANC__DICOM_WEB__SSL: "true"
            ORTHANC__DICOM_WEB__STUDIESMETADATA: "MainDicomTags"
            ORTHANC__DICOM_WEB__SERIESMETADATA: "Full"
            ORTHANC__BUILTIN__DECODER__TRANSCODER__ORDER: "Before"

    orthanctoolsjspacs:
        image: osimis/orthanc:23.4.0
        ports: ["8043:8042"]
        container_name: orthanctoolsjspacs
        restart: unless-stopped
        volumes: ["orthancpacs:/var/lib/orthanc/db:Z"]
        networks:
          - internal
        environment:
            ORTHANC__NAME: "OrthancPacs"
            ORTHANC__DICOM_MODALITIES_IN_DATABASE: "true"
            ORTHANC__REGISTERED_USERS: |
                    {"salim": "salim"}

volumes:
        orthanc:
        orthancpacs:
        orthanctoolsjs:
        postgres:`

**Comment by salimkanoun** [comment]
Hi, just check is the http is working, the https should me managed in a
reverse proxy outside Orthanctools js

**Comment by tanimraja1** [comment]
http works fine but https is not working, i'm using apache httpd and here's my config
`<VirtualHost *:80>
    ServerName your_domain.com
    Redirect permanent / https://your_domain.com:8080/
</VirtualHost>

<VirtualHost *:443>
    ServerName your_domain.com

    SSLEngine on
    SSLCertificateFile /path/to/your_ssl_certificate.crt
    SSLCertificateKeyFile /path/to/your_ssl_private_key.key

    ProxyPreserveHost On
    ProxyPass /orthanc/ http://orthanctoolsjs:8080/
    ProxyPassReverse /orthanc/ http://orthanctoolsjs:8080/

    <Location /orthanc/>
        ProxyPassReverse /
        RequestHeader unset Authorization
    </Location>

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule /orthanc/(.*) ws://orthanctoolsjs:8080/$1 [P,L]

    ProxyPass /orthanc/ws/ ws://orthanctoolsjs:8080/
    ProxyPassReverse /orthanc/ws/ ws://orthanctoolsjs:8080/
</VirtualHost>
`

**Comment by salimkanoun** [comment]
I guess you should use localhost domain (as container is exposed to host) rather than Orthanctoolsjs domain (which stand for inter service communication)

Anyway reverse proxying orthanc tools js is not an issue related to this project, so i close the issue
