### ISSUE TITLE
IMPORT QUERY LIST not quite functional

### ISSUE THREAD

**Issue by ai-fabric** [salimkanoun/Orthanc-Tools-JS#858]
While importing list as CSV , date format aren't well handled.
It means that "20261206" becomes 20261206 and while retrieving dicoms , this provide an error " unknown date format" 
This is exactly the same if you use the agenda in order to pick up the date through the graphic interface.
Unexpectedly , if you use the manual query one by one , the date format is well handled nevertheless.

**Comment by salimkanoun** [comment]
Hum I don't reproduce this issue please check your on the latest sources
