### ISSUE TITLE
SFTP for large bundle of image

### ISSUE THREAD

**Issue by ai-fabric** [salimkanoun/Orthanc-Tools-JS#859]
download through web interface is sometimes quite confusing.
I did try several times and it did freeze after a random delay.
So is it possible to provide a FTP <=> user in order to resume transferts ?

I also did try DAV , http , and so on . Nevertheless in secured environnements , this protocols could be locked for security reasons toward a server.

**Comment by salimkanoun** [comment]
Sftp/webdav/FTP transfert are likely to be broken as we didn't pushed to much effort to maintain it.

I'm might taking the decision to recreate the backend from scratch and these feature won't be ported to the new backend

There no reason to not be able to retrieve a large amount of data either from browser or from a script calling the api
