### ISSUE TITLE
Problème d'affichage OrthancContent

### ISSUE THREAD

**Issue by beber32** [salimkanoun/Orthanc-Tools-JS#90]
Lorsqu'on import un patient avec plusieurs Studies avec le module d'import toutes les studies sont affichées. Mais lorsqu'on cherche le patient avec OrthancContent, seul 1 study est affichée.

**Comment by salimkanoun** [comment]
Bizarre, faudrait revoir ca, les deux modules sont indépendants, je doute que ca soit possible.
Une hypothèse : tu avait peut etre un filtre de data qui etait activé dans OrthancContent ce qui fait que tu n'a pas trouvé l'étude qui a été importée dans import
