### ISSUE TITLE
Taille colonne maximale

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Orthanc-Tools-JS#99]
Si le patient a un nom tres long
ou si le study description est tres long,
Les tables prennet trop de largeur.

Il faudrait fixer la taille maximal d'une colonne, voir si y a des mode de visualisation d'une cellule qui n'afficherai pas tout (au survol par exemple)

Faudrait definir une solution et l'appliquer à toutes les tables

**Comment by beber32** [comment]
Je n'ai pas réussi à coriger ce pb. 
Une solution est de placer les popovers à gauche et non en dessous.

**Comment by salimkanoun** [comment]
J'ai enelvé le maxWith 50px qu(il y a avait dans certaine colonne de la table study.

Maitenant boostrap table fait comme il peux quitte a passer en overflow, à voir à l'usage
